/**
 * The lite page's own words. Everything else it shows (findings, client
 * notes, `.conf` comments) comes from the main catalogue via
 * `generated/strings.ts`, so the two sites say the same thing about a config.
 */

export const UI = {
  ru: {
    "lite.title": "Any Tech ARCHITECT Lite",
    "lite.subtitle": "Генератор параметров обфускации AmneziaWG. Один файл, работает без сети.",
    "lite.rare":
      "Это облегчённая сборка, и обновляется она редко. Для актуальной версии с XRay, симулятором, MergeKeys и FAQ используйте полный сайт:",
    "lite.version": "Версия протокола",
    "lite.client": "Клиент",
    "lite.release": "Сборка клиента",
    "lite.releaseCurrent": "текущая",
    "lite.profile": "Профиль мимикрии",
    "lite.intensity": "Интенсивность",
    "lite.intensity.low": "Низкая",
    "lite.intensity.medium": "Средняя",
    "lite.intensity.high": "Высокая",
    "lite.junk": "Junk-пакетов (Jc)",
    "lite.region": "Регион хостов",
    "lite.region.any": "Любой",
    "lite.region.ru": "Россия",
    "lite.region.global": "Мир",
    "lite.region.eu": "Европа",
    "lite.region.uk": "Великобритания",
    "lite.region.by": "Беларусь",
    "lite.region.cn": "Китай",
    "lite.host": "Свой хост",
    "lite.hostPlaceholder": "пусто: из базы",
    "lite.mtu": "MTU",
    "lite.options": "Параметры",
    "lite.mimicAll": "Профиль во всех I1-I5",
    "lite.routerMode": "Режим роутера",
    "lite.extreme": "Предельные значения",
    "lite.tags": "Теги цепочки",
    "lite.awg3": "Блок 3.x",
    "lite.hpk": "Защита заголовков",
    "lite.cpa": "Добавочный паддинг",
    "lite.timings": "Случайные таймеры",
    "lite.trailers": "Случайные хвосты",
    "lite.cookies": "Без cookie",
    "lite.narrowH": "Узкие H1-H4",
    "lite.sameS": "Одинаковые S1-S4",
    "lite.generate": "Сгенерировать",
    "lite.copy": "Копировать",
    "lite.copied": "Скопировано",
    "lite.download": "Скачать .conf",
    "lite.notes": "Про этот клиент",
    "lite.problems": "Проверка",
    "lite.check": "Проверить конфиг",
    "lite.checkHint": "Вставьте .conf, собранный где угодно. Он никуда не отправляется.",
    "lite.checkButton": "Проверить",
    "lite.checkClean": "Замечаний нет.",
    "lite.error": "Не получилось",
    "lite.build": "Версия {version}, сборка {date}",
    "lite.source": "Исходники",
    "lite.lang": "English",
  },
  en: {
    "lite.title": "Any Tech ARCHITECT Lite",
    "lite.subtitle": "AmneziaWG obfuscation parameter generator. One file, works offline.",
    "lite.rare":
      "This is the lightweight build, and it is updated rarely. For the current version with XRay, the simulator, MergeKeys and the FAQ, use the full site:",
    "lite.version": "Protocol version",
    "lite.client": "Client",
    "lite.release": "Client build",
    "lite.releaseCurrent": "current",
    "lite.profile": "Mimicry profile",
    "lite.intensity": "Intensity",
    "lite.intensity.low": "Low",
    "lite.intensity.medium": "Medium",
    "lite.intensity.high": "High",
    "lite.junk": "Junk packets (Jc)",
    "lite.region": "Host region",
    "lite.region.any": "Any",
    "lite.region.ru": "Russia",
    "lite.region.global": "Global",
    "lite.region.eu": "Europe",
    "lite.region.uk": "United Kingdom",
    "lite.region.by": "Belarus",
    "lite.region.cn": "China",
    "lite.host": "Own host",
    "lite.hostPlaceholder": "empty: from the database",
    "lite.mtu": "MTU",
    "lite.options": "Options",
    "lite.mimicAll": "Profile in all of I1-I5",
    "lite.routerMode": "Router mode",
    "lite.extreme": "Extreme values",
    "lite.tags": "Chain tags",
    "lite.awg3": "3.x block",
    "lite.hpk": "Header protection",
    "lite.cpa": "Extra padding",
    "lite.timings": "Random timers",
    "lite.trailers": "Random trailers",
    "lite.cookies": "No cookies",
    "lite.narrowH": "Narrow H1-H4",
    "lite.sameS": "Identical S1-S4",
    "lite.generate": "Generate",
    "lite.copy": "Copy",
    "lite.copied": "Copied",
    "lite.download": "Download .conf",
    "lite.notes": "About this client",
    "lite.problems": "Check",
    "lite.check": "Check a config",
    "lite.checkHint": "Paste a .conf built anywhere. It is not sent anywhere.",
    "lite.checkButton": "Check",
    "lite.checkClean": "Nothing to report.",
    "lite.error": "That did not work",
    "lite.build": "Version {version}, built {date}",
    "lite.source": "Source",
    "lite.lang": "Русский",
  },
} as const;
