/**
 * Prepares the data the lite build carries instead of the full modules.
 *
 *   bun scripts/lite/prepare.ts
 *
 * Two files under `src/lite/generated/`, both committed so the tree
 * type-checks without running anything first, and both checked against their
 * sources by `src/lite/__tests__/lite.test.ts`, so a stale copy fails CI
 * rather than shipping:
 *
 *   pools.ts    every host list the generator can ask for, already resolved.
 *               The domain database is 818 KB of records with fields the
 *               generator never reads; what it reads is one list per region,
 *               role and DNS type, picked from at random. Those lists, with
 *               the same fallbacks `pickHost` applies, are a small fraction
 *               of it, and drawing from them gives the same distribution.
 *
 *   strings.ts  the catalogue keys the lite page shows: findings, client
 *               notes and the `.conf` comments, in both languages. The rest
 *               of the catalogue describes pages the lite build does not have.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { hostsFor, REGIONS, DOMAINS } from "../../src/shared/domains";
import ru from "../../src/i18n/locales/ru";
import en from "../../src/i18n/locales/en";
import type { DnsQueryType, DomainQuery, DomainRole } from "../../src/types/domain";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.resolve(here, "../../src/lite/generated");

/** Roles the AmneziaWG generator asks for (generator/utils.ts PROFILE_ROLE). */
export const LITE_ROLES: readonly DomainRole[] = ["quic", "tls", "dtls", "sip", "stun", "dns"];

/** The DNS profile asks for these types and no others (profiles/dns.ts). */
export const LITE_DNS_TYPES: readonly DnsQueryType[] = ["A", "AAAA"];

export const LITE_REGIONS = ["any", ...REGIONS] as const;

/** Catalogue keys the lite page needs, by prefix or by name. */
export const STRING_PREFIXES = ["find.", "client.", "conf."] as const;
export const STRING_KEYS = ["gen.profile.random"] as const;

/** The key a lite lookup uses: region, role, DNS type. */
export function poolKey(region: string, role: string, dnsType = ""): string {
  return `${region}|${role}|${dnsType}`;
}

/** What `pickHost` would choose from for a query, fallbacks included. */
export function effectivePool(query: DomainQuery): readonly string[] {
  const exact = hostsFor(query);
  if (exact.length) return exact;
  const relaxed = hostsFor({ ...query, allowUnknown: true });
  if (relaxed.length) return relaxed;
  const anyRegion = hostsFor({ role: query.role, allowUnknown: true });
  return anyRegion.length ? anyRegion : [DOMAINS[0]!.host];
}

export function allPools(): Map<string, readonly string[]> {
  const pools = new Map<string, readonly string[]>();
  for (const region of LITE_REGIONS) {
    for (const role of LITE_ROLES) {
      const types: (DnsQueryType | undefined)[] = role === "dns" ? [...LITE_DNS_TYPES] : [undefined];
      for (const dnsType of types) {
        const query: DomainQuery = {
          regions: region === "any" ? undefined : [region],
          role,
          dnsType,
        };
        pools.set(poolKey(region, role, dnsType ?? ""), effectivePool(query));
      }
    }
  }
  return pools;
}

export function stringSubset(catalog: Record<string, unknown>): Record<string, unknown> {
  const picked: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(catalog)) {
    if (STRING_PREFIXES.some((p) => key.startsWith(p)) || (STRING_KEYS as readonly string[]).includes(key)) {
      picked[key] = value;
    }
  }
  return picked;
}

function write(file: string, body: string): void {
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, file), body);
  const kb = (Buffer.byteLength(body) / 1024).toFixed(1);
  console.log(`[lite] ${file}: ${kb} KB`);
}

const HEADER = "// Generated by scripts/lite/prepare.ts. Do not edit; run `bun run lite:prepare`.\n";

if (import.meta.main) {
  const pools = allPools();

  // One table of names, and each pool as indices into it.
  const hosts = [...new Set([...pools.values()].flat())].sort();
  const index = new Map(hosts.map((h, i) => [h, i]));
  const encoded: Record<string, string> = {};
  for (const [key, list] of pools) {
    encoded[key] = list.map((h) => index.get(h)!.toString(36)).join(",");
  }

  write(
    "pools.ts",
    HEADER +
      `export const HOSTS: readonly string[] = ${JSON.stringify(hosts)};\n\n` +
      `/** Region|role|dnsType -> indices into HOSTS, base 36, comma separated. */\n` +
      `export const POOLS: Readonly<Record<string, string>> = ${JSON.stringify(encoded, null, 1)};\n`,
  );

  write(
    "strings.ts",
    HEADER +
      `export const STRINGS = ${JSON.stringify({ ru: stringSubset(ru), en: stringSubset(en) })} as const;\n`,
  );
}
